/**
 * Credence Documentation & Sovereign Blog Zero-Build Application Engine
 * Pure Vanilla Modern ES Module — 0 npm dependencies, 0 build tools.
 */

// Canonical ecosystem version
export const CURRENT_ECOSYSTEM_VERSION = 'v2.21.0';

// Navigation structure and complete catalog
export const DOCS_REGISTRY = [
  {
    category: "Getting Started",
    items: [
      { id: "docs/intro", title: "Introduction & Overview", path: "docs/intro.md", desc: "Welcome to Credence, key concepts, and progressive on-ramp.", keywords: ["intro", "overview", "welcome", "philosophy", "grounding", "basics", "start", "truth", "ethics", "ai"] },
      { id: "docs/quickstart", title: "Quickstart & Installation", path: "docs/quickstart.md", desc: "Install Credence, set API keys, and run your first audit in 60 seconds.", keywords: ["quickstart", "install", "curl", "poetry", "docker", "gemini", "api key", "first audit", "setup", "run", "cli"] },
      { id: "docs/topic-index", title: "Topic Index & Concept Directory", path: "docs/topic-index.md", desc: "The Marbles in the Oatmeal: complete categorized cheat sheet and index.", keywords: ["index", "cheat sheet", "search", "topics", "sitemap", "directory", "marbles", "lookup", "concepts", "all", "reference", "find"] },
      { id: "docs/sitemap", title: "Ecosystem Master Sitemap", path: "docs/sitemap.md", desc: "Visual and structural sitemap covering all sovereign domains, playgrounds, invariants, and guides.", keywords: ["sitemap", "map", "directory", "tree", "overview", "domains", "navigation", "all pages", "structure"] },
      { id: "docs/feature-parity", title: "Universal Feature Parity", path: "docs/feature-parity.md", desc: "Synchronous 4-way parity across CLI, FastMCP, TUI, and Web UI.", keywords: ["parity", "interfaces", "cli", "tui", "mcp", "web", "terminal", "browser"] },
      { id: "docs/roadmap", title: "Roadmap & Horizons", path: "docs/roadmap.md", desc: "Current development roadmap, completed milestones, and upcoming horizons.", keywords: ["roadmap", "backlog", "future", "milestones", "features", "horizons"] },
      { id: "docs/changelog", title: "Release Changelog", path: "docs/changelog.md", desc: "Version history, updates, and release notes across releases.", keywords: ["changelog", "releases", "versions", "history", "notes"] }
    ]
  },
  {
    category: "Platform Portability & Sovereignty",
    items: [
      { id: "docs/portability/multi-model-adapters", title: "Multi-Model Provider Adapters", path: "docs/portability/multi-model-adapters.md", desc: "Plugging in Gemini, Claude 3.7, GPT-4o, DeepSeek-R1, and local Ollama.", keywords: ["models", "claude", "gpt-4o", "deepseek", "ollama", "adapters", "providers"] },
      { id: "docs/portability/gemini-economic-rationale", title: "ADR: Why Gemini 3.7 Flash", path: "docs/portability/gemini-economic-rationale.md", desc: "Economic and architectural rationale for Gemini 3.7 Flash thinking models.", keywords: ["gemini", "gemini-3.7-flash", "thinking", "adr", "economics", "pricing"] },
      { id: "docs/portability/multi-cloud-deployment", title: "Multi-Cloud (AWS, Azure, Hetzner, K8s)", path: "docs/portability/multi-cloud-deployment.md", desc: "Deploying Credence to AWS Fargate, Azure Container Apps, Hetzner, and K8s.", keywords: ["aws", "azure", "hetzner", "kubernetes", "k8s", "docker", "cloud", "deploy"] },
      { id: "docs/portability/universal-agent-interop", title: "Universal Agent Interoperability", path: "docs/portability/universal-agent-interop.md", desc: "Connecting Windsurf, Cline, Claude Desktop, Cursor, and custom agent swarms.", keywords: ["windsurf", "cline", "cursor", "claude", "agents", "interop", "mcp"] },
      { id: "docs/portability/local-llm-airgap", title: "Zero-Cloud Sovereign Local LLMs", path: "docs/portability/local-llm-airgap.md", desc: "100% private, zero-cloud air-gapped evaluation with Ollama and vLLM.", keywords: ["local", "ollama", "vllm", "airgap", "private", "offline", "sovereign"] }
    ]
  },
  {
    category: "Interactive Playgrounds",
    items: [
            { id: "docs/lab-content-evolution", title: "🎮 Playground 13: Content Evolution Lab", path: "docs/lab-content-evolution.md", desc: "Live in-browser content modification simulator tracking score trajectory shifts across edits.", keywords: ["playground", "interactive", "evolution", "diff", "correction", "stealth edit"] },
      { id: "docs/lab-badge-security", title: "🎮 Playground 14: Adversarial Badge Lab", path: "docs/lab-badge-security.md", desc: "Break the Badge: live interactive sandbox testing Bait-and-Switch and signature forgery defenses.", keywords: ["playground", "interactive", "badge", "red team", "break the badge", "security", "attack"] },
      { id: "docs/playground", title: "🎮 Interactive Zero-Build Playgrounds", path: "docs/playground.md", desc: "12 in-browser simulators: 13-node mesh, SimHash-64, Saturation, Token Governor & Verifier.", keywords: ["playground", "interactive", "simulator", "demo", "browser", "try", "mesh", "simhash", "webcrypto"] }
    ]
  },
  {
    category: "Feature Walkthroughs",
    items: [
      { id: "docs/walkthroughs/01-auditing-webpages-and-text", title: "Auditing Webpages & Text", path: "docs/walkthroughs/01-auditing-webpages-and-text.md", desc: "How to audit any URL or raw text using the CLI and interpret findings.", keywords: ["audit", "cli", "text", "url", "command", "report", "suspicion", "violations"] },
      { id: "docs/walkthroughs/02-zero-trust-feed-sifting", title: "Zero-Trust Feed Sifting", path: "docs/walkthroughs/02-zero-trust-feed-sifting.md", desc: "Filter RSS/Atom feeds against promotional astroturfing and topic entropy collapse.", keywords: ["sifter", "rss", "atom", "feed", "entropy", "pizza hut", "astroturf", "filter"] },
      { id: "docs/walkthroughs/03-p2p-mesh-consensus", title: "P2P Mesh Consensus", path: "docs/walkthroughs/03-p2p-mesh-consensus.md", desc: "How decentralized nodes gossip signed attestations and reach consensus.", keywords: ["mesh", "p2p", "consensus", "gossip", "attestation", "decentralized", "nodes"] },
      { id: "docs/walkthroughs/04-morning-digest-briefings", title: "Morning Epistemic Digest", path: "docs/walkthroughs/04-morning-digest-briefings.md", desc: "Generate daily 24-hour executive news briefings and terminal digests.", keywords: ["digest", "morning", "briefing", "daily", "summary", "executive", "news"] },
            { id: "docs/walkthroughs/06-embeddable-badges-and-docs-self-auditing", title: "06. Embeddable Badges & Self-Auditing", path: "docs/walkthroughs/06-embeddable-badges-and-docs-self-auditing.md", desc: "Embed <credence-badge>, configure anti-tamper WebCrypto gates, and run differential CI/CD audits.", keywords: ["badge", "embed", "widget", "dogfood", "audit-docs", "webcrypto", "tamper", "receipt"] },
      { id: "docs/walkthroughs/05-migrating-from-v1-to-v2", title: "Migrating from v1.x to v2.0.0", path: "docs/walkthroughs/05-migrating-from-v1-to-v2.md", desc: "Step-by-step migration guide for upgrading custom scripts and configs to Credence v2.0.0.", keywords: ["migration", "v2", "upgrade", "breaking changes", "ontology", "compute"] }
    ]
  },
  {
    category: "Hands-On Tutorials",
    items: [
      { id: "docs/tutorials/01-clickbait-teardown", title: "01. Clickbait Teardown", path: "docs/tutorials/01-clickbait-teardown.md", desc: "Step-by-step forensic teardown of sensationalist clickbait and unnamed claims.", keywords: ["tutorial", "clickbait", "teardown", "sources", "fallacy", "example"] },
      { id: "docs/tutorials/02-satire-vs-disinformation", title: "02. Satire vs Disinformation", path: "docs/tutorials/02-satire-vs-disinformation.md", desc: "Navigating Poe's Law, satire neutralization, and SPJ-1.6 cloaking defense.", keywords: ["satire", "disinformation", "poe", "onion", "parody", "cloaking"] },
      { id: "docs/tutorials/03-claude-cursor-fastmcp", title: "03. Claude & Cursor FastMCP", path: "docs/tutorials/03-claude-cursor-fastmcp.md", desc: "Connect Credence FastMCP server to Claude Desktop and Cursor IDE in 2 minutes.", keywords: ["claude", "cursor", "fastmcp", "config", "json", "setup", "tools"] },
      { id: "docs/tutorials/04-sovereign-org-scaffolding", title: "04. Sovereign Org Scaffolding", path: "docs/tutorials/04-sovereign-org-scaffolding.md", desc: "Scaffold sovereign white-label federation organizations with credence init-org.", keywords: ["init-org", "white-label", "federation", "organization", "terraform"] },
      { id: "docs/tutorials/05-mesh-quickstart", title: "05. 3-Node Mesh Quickstart", path: "docs/tutorials/05-mesh-quickstart.md", desc: "Spin up a local 3-node P2P mesh cluster and observe real-time gossip.", keywords: ["mesh", "3-node", "p2p", "cluster", "gossip", "docker"] },
      { id: "docs/tutorials/06-thirteen-node-chaos-lab", title: "06. 13-Node Chaos Lab", path: "docs/tutorials/06-thirteen-node-chaos-lab.md", desc: "Run a 13-node Watts-Strogatz chaos simulation with Byzantine cartel attacks.", keywords: ["13-node", "chaos", "byzantine", "sybil", "watts-strogatz", "cartel"] },
      { id: "docs/tutorials/07-air-gapped-and-adhoc-mesh", title: "07. Air-Gapped Truth Bundles", path: "docs/tutorials/07-air-gapped-and-adhoc-mesh.md", desc: "Export and verify signed truth attestations on offline USB sneakernets.", keywords: ["airgap", "sneakernet", "usb", "offline", "bundle", "verify"] },
      { id: "docs/tutorials/08-sybil-cartel-demolition", title: "08. Sybil Cartel Demolition", path: "docs/tutorials/08-sybil-cartel-demolition.md", desc: "How weighted medians and Galileo Rule neutralize coordinated cartel attacks.", keywords: ["sybil", "cartel", "attack", "defense", "weighted median", "galileo"] },
      { id: "docs/tutorials/09-zero-trust-feed-sifter-digest", title: "09. Zero-Trust Feed Sifter & Digest", path: "docs/tutorials/09-zero-trust-feed-sifter-digest.md", desc: "Full guide to automated morning news briefings and feed health scoring.", keywords: ["sifter", "digest", "rss", "briefing", "morning", "automation"] },
      { id: "docs/tutorials/10-reusable-live-e2e-and-mesh-gauntlet", title: "10. Reusable Live E2E & Mesh Gauntlet", path: "docs/tutorials/10-reusable-live-e2e-and-mesh-gauntlet.md", desc: "Run live rotating test suites across multi-category news corpora.", keywords: ["e2e", "gauntlet", "live", "testing", "rotating", "corpus"] },
      { id: "docs/tutorials/11-autonomous-node-germination-and-swarm-ignition", title: "11. Node Germination & Swarm Ignition", path: "docs/tutorials/11-autonomous-node-germination-and-swarm-ignition.md", desc: "5-second node germination: keys, genesis inoculation, and burst auditing.", keywords: ["germination", "genesis", "miracle-gro", "ignition", "bootstrap", "seeds"] },
      { id: "docs/tutorials/12-climbing-the-epistemic-tiers", title: "12. Climbing the Epistemic Tiers", path: "docs/tutorials/12-climbing-the-epistemic-tiers.md", desc: "Earn empirical expertise, build domain authority, and climb P2P leaderboards.", keywords: ["tiers", "reputation", "leaderboard", "expertise", "quality", "rank"] },
      { id: "docs/tutorials/13-discord-alerting-and-basement-monitoring", title: "13. Discord Alerts & Basement Ops", path: "docs/tutorials/13-discord-alerting-and-basement-monitoring.md", desc: "Setup real-time Discord webhook notifications for breaking high-suspicion stories.", keywords: ["discord", "webhook", "alerts", "monitoring", "basement", "notifications"] },
      { id: "docs/tutorials/14-operator-security-and-admin-workstation", title: "14. Operator Security & Admin Workstation", path: "docs/tutorials/14-operator-security-and-admin-workstation.md", desc: "Bootstrapping operator authentication, managing AI cost budgets, and operating the Web Admin Command Deck.", keywords: ["operator", "security", "admin", "workstation", "oauth", "oidc", "token", "budget", "emergency stop", "tutorial"] }
    ]
  },
  {
    category: "Developer Cookbooks",
    items: [
            { id: "docs/cookbooks/hetzner-vps-and-systemd-setup", title: "Hetzner VPS & systemd Daemon Setup", path: "docs/cookbooks/hetzner-vps-and-systemd-setup.md", desc: "Deploying autonomous 24/7 background daemons on low-cost VPS.", keywords: ["hetzner", "systemd", "vps", "daemons", "cookbook"] },
      { id: "docs/cookbooks/local-dev-to-cloud-run-workflow", title: "Local Dev to Cloud Run Workflow", path: "docs/cookbooks/local-dev-to-cloud-run-workflow.md", desc: "Fast iteration loops from local poetry test to production Cloud Run.", keywords: ["cloudrun", "workflow", "local dev", "deploy", "cookbook"] },
      { id: "docs/cookbooks/aws-and-flyio-deployment", title: "AWS & Fly.io Deployment Recipes", path: "docs/cookbooks/aws-and-flyio-deployment.md", desc: "Container deployment recipes for alternate multi-cloud providers.", keywords: ["aws", "flyio", "cloud", "deployment", "cookbook"] },
      { id: "docs/cookbooks/edge-caching-browser-extension", title: "Edge Caching & Browser Extension", path: "docs/cookbooks/edge-caching-browser-extension.md", desc: "Configuring cache-control headers and extension background sync.", keywords: ["cache", "extension", "edge", "cookbook"] },
      { id: "docs/cookbooks/multi-tenant-org-subdomain-federation", title: "Multi-Tenant Org Subdomain Federation", path: "docs/cookbooks/multi-tenant-org-subdomain-federation.md", desc: "Configuring white-label custom domain federation routing.", keywords: ["federation", "subdomains", "orgs", "cookbook"] },
      { id: "docs/cookbooks/agentic-epistemic-brake", title: "Agentic Epistemic Brake", path: "docs/cookbooks/agentic-epistemic-brake.md", desc: "Halting LLM agent action loops when grounded confidence falls below threshold.", keywords: ["brake", "langgraph", "crewai", "agent", "guardrail", "action"] },
      { id: "docs/cookbooks/taxonomy-engineering", title: "Taxonomy Rule Engineering 101", path: "docs/cookbooks/taxonomy-engineering.md", desc: "How to author custom namespaced YAML taxonomy catalogs with test suites.", keywords: ["yaml", "taxonomy", "rules", "authoring", "ethics", "fallacies"] },
      { id: "docs/cookbooks/morning-feed-sifter", title: "Automated Morning Feed Sifter", path: "docs/cookbooks/morning-feed-sifter.md", desc: "Cron recipe for scheduled morning news sifting and markdown briefings.", keywords: ["cron", "sifter", "morning", "automation", "briefing", "schedule"] },
      { id: "docs/cookbooks/financial-disclosures", title: "Auditing Financial 10-K Filings", path: "docs/cookbooks/financial-disclosures.md", desc: "Audit non-GAAP metrics and earnings disclosures with Ultra thinking profile.", keywords: ["financial", "10-k", "sec", "ebitda", "earnings", "ultra", "thinking"] },
      { id: "docs/cookbooks/defining-and-adopting-custom-standards", title: "Defining & Adopting Custom Standards in Credence", path: "docs/cookbooks/defining-and-adopting-custom-standards.md", desc: "Complete operator and researcher handbook for authoring epistemic rule catalogs, executing the synthetic benchmark gauntlet, and achieving autonomous decentralized mesh adoption.", keywords: ["standards", "custom", "cookbook", "authoring", "rules"] }
    ]
  },
  {
    category: "Agentic Engineering & Workflows",
    items: [
      { id: "docs/agentic/01-antigravity-pair-programming-paradigm", title: "01. Antigravity Pair-Programming", path: "docs/agentic/01-antigravity-pair-programming-paradigm.md", desc: "Autonomous multi-agent pair programming with Google Antigravity SDK.", keywords: ["antigravity", "pair programming", "sdk", "subagents", "agentic", "gemini"] },
      { id: "docs/agentic/02-continuous-learning-and-invariant-synthesis", title: "02. /learn & Invariant Synthesis", path: "docs/agentic/02-continuous-learning-and-invariant-synthesis.md", desc: "Capturing agent learnings, invariant synthesis, and knowledge governance.", keywords: ["learn", "invariants", "synthesis", "knowledge", "governance", "rules"] },
      { id: "docs/agentic/03-hermetic-testing-and-zero-npm-guardrails", title: "03. Hermetic Testing & Zero-npm", path: "docs/agentic/03-hermetic-testing-and-zero-npm-guardrails.md", desc: "Hermetic offline test suites and zero-npm static web guardrails.", keywords: ["hermetic", "testing", "zero-npm", "offline", "pytest", "guardrails"] },
      { id: "docs/agentic/04-multi-model-pareto-and-token-governance", title: "04. Multi-Model Pareto & Token Governor", path: "docs/agentic/04-multi-model-pareto-and-token-governance.md", desc: "Token budget governor, circuit breakers, and cost Pareto frontier.", keywords: ["pareto", "tokens", "governor", "circuit breaker", "budget", "cost", "headroom"] },
      { id: "docs/agentic/05-fastmcp-dual-transport-and-four-way-parity", title: "05. FastMCP & 4-Way Parity", path: "docs/agentic/05-fastmcp-dual-transport-and-four-way-parity.md", desc: "FastMCP 2.0 dual transport (stdio and SSE) and 4-way feature parity.", keywords: ["fastmcp", "transport", "stdio", "sse", "parity", "mcp", "streaming"] },
      { id: "docs/agentic/06-the-demotion-highway-and-invariant-lifecycle", title: "06. Demotion Highway & Lifecycle", path: "docs/agentic/06-the-demotion-highway-and-invariant-lifecycle.md", desc: "Invariant lifecycle state machine, Class Alpha/Beta/Gamma ranking, and automated demotion scanner.", keywords: ["demotion", "highway", "lifecycle", "invariants", "taxonomy", "alpha", "beta", "gamma", "subagents", "scanner"] },
      { id: "docs/agentic/07-bootstrapping-agentic-workflows-with-invariants", title: "07. Bootstrapping Agentic Invariants", path: "docs/agentic/07-bootstrapping-agentic-workflows-with-invariants.md", desc: "How to extract and bootstrap Universal Agentic Invariants to supercharge AI pair programming in any new project.", keywords: ["bootstrap", "starter pack", "universal", "invariants", "agents.md", "portable", "workflow", "governance"] }
    ]
  },
  {
    category: "Client Ecosystem & Integrations",
    items: [
      { id: "docs/integrations/browser-extension-mv3", title: "Zero-Build Browser Extension", path: "docs/integrations/browser-extension-mv3.md", desc: "Vanilla Manifest V3 browser extension for live in-tab credibility badges.", keywords: ["extension", "chrome", "manifest v3", "browser", "badge", "zero-build"] },
      { id: "docs/integrations/cli-scripting-guide", title: "CLI Automation & Shell Scripts", path: "docs/integrations/cli-scripting-guide.md", desc: "jq pipelines, GitHub Actions CI PR gates, and headless automation.", keywords: ["cli", "jq", "scripts", "bash", "github actions", "ci", "pr gate"] },
      { id: "docs/integrations/tui-workstation", title: "Textual TUI Workstation", path: "docs/integrations/tui-workstation.md", desc: "Full-screen keyboard-driven terminal IDE with interactive citation inspector.", keywords: ["tui", "textual", "terminal", "workstation", "keybindings", "keyboard"] }
    ]
  },
  {
    category: "Operations & Self-Hosting",
    items: [
      { id: "docs/operations/deployment-prerequisites", title: "Master Deployment Prerequisites", path: "docs/operations/deployment-prerequisites.md", desc: "Complete prerequisite checklists, credential matrices, and CLI commands across all deployment topologies.", keywords: ["prerequisites", "setup", "requirements", "credentials", "cloud run", "docker", "kubernetes", "cloudflare", "bare metal", "checklist"] },
      { id: "docs/operations/single-vs-dual-project-gcp", title: "Single vs Dual-Project GCP", path: "docs/operations/single-vs-dual-project-gcp.md", desc: "Runbook for single partitioned GCP project vs hard dual-project isolation.", keywords: ["gcp", "dual project", "single project", "dev", "prod", "isolation", "terraform", "runbook", "boundaries"] },
      { id: "docs/operations/multi-environment-boundaries-and-deployments", title: "Multi-Environment Boundaries", path: "docs/operations/multi-environment-boundaries-and-deployments.md", desc: "Project, domain, and data boundary isolation with launch parity.", keywords: ["environments", "boundaries", "dev", "prod", "parity", "deploy", "secrets", "ci cd"] },
      { id: "docs/operations/vendor-agnostic-self-hosting-and-docker", title: "Vendor-Agnostic Self-Hosting", path: "docs/operations/vendor-agnostic-self-hosting-and-docker.md", desc: "Running sovereign Credence nodes across Docker, Bare Metal Linux, VPS, and Kubernetes.", keywords: ["self-host", "vendor agnostic", "docker", "vps", "hetzner", "ovh", "aws", "linode", "sovereign"] },
      { id: "docs/operations/docker-compose-quickstart", title: "Docker Compose Quickstart", path: "docs/operations/docker-compose-quickstart.md", desc: "Quickstart guide for launching a sovereign node or full-stack cluster locally in 5 minutes.", keywords: ["docker compose", "quickstart", "local", "planetary", "postgres", "minio", "valkey"] },
      { id: "docs/operations/kubernetes-and-helm-deployment", title: "Kubernetes & Helm Deployment", path: "docs/operations/kubernetes-and-helm-deployment.md", desc: "Cloud-native manifests, PVC storage, and ingress routing.", keywords: ["kubernetes", "k8s", "helm", "manifests", "ingress", "pvc", "cloud native"] },
      { id: "docs/operations/blob-storage-r2", title: "Cloudflare R2 Blob Storage", path: "docs/operations/blob-storage-r2.md", desc: "S3-compatible zero-egress Cloudflare R2 storage for forensic snapshots.", keywords: ["r2", "blob storage", "s3", "cloudflare", "cas", "snapshots", "zero egress"] },
      { id: "docs/operations/pipeline-and-build-optimization", title: "Pipeline & Build Optimization", path: "docs/operations/pipeline-and-build-optimization.md", desc: "Workstation tuning, pytest-xdist parallelization, build context exclusions, and sub-40s QA gates.", keywords: ["pipeline", "ci", "cd", "pytest", "xdist", "docker", "gcloudignore", "buildkit", "optimization", "performance", "check", "sub-40s", "speed"] },
      { id: "docs/operations/raspberry-pi-homelab", title: "Raspberry Pi & HomeLab Node", path: "docs/operations/raspberry-pi-homelab.md", desc: "Setting up a $0.00/mo self-hosted node on a Raspberry Pi 4/5.", keywords: ["raspberry pi", "homelab", "pi", "arm64", "self-host", "low power"] },
      { id: "docs/operations/tailscale-wireguard-mesh", title: "Tailscale & WireGuard Peering", path: "docs/operations/tailscale-wireguard-mesh.md", desc: "Forming secure private P2P mesh overlays across home and cloud servers.", keywords: ["tailscale", "wireguard", "vpn", "overlay", "peering", "private"] },
      { id: "docs/operations/database-pruning-wal", title: "Database Pruning & WAL Care", path: "docs/operations/database-pruning-wal.md", desc: "SQLite WAL optimization, checkpointing, and 30-day token record pruning.", keywords: ["sqlite", "wal", "database", "pruning", "retention", "cleanup", "sql"] },
      { id: "docs/operations/customizations-and-upstream-sovereignty", title: "Customizations vs. Upstream Core", path: "docs/operations/customizations-and-upstream-sovereignty.md", desc: "Maintaining local sovereignty while pulling updates from upstream repos.", keywords: ["customizations", "upstream", "git", "fork", "sovereignty", "merge"] },
      { id: "docs/blueprints/cloudrun-scale-to-zero-cold-start-optimization", title: "Cloud Run Cold Start Optimization", path: "docs/blueprints/cloudrun-scale-to-zero-cold-start-optimization.md", desc: "The 5-pillar architectural framework for sub-2.5s serverless cold starts on scale-to-zero Cloud Run containers.", keywords: ["cold start", "scale to zero", "cloud run", "serverless", "startup cpu boost", "compileall", "bytecode", "probe", "optimization", "performance", "gcp", "blueprint"] },
      { id: "docs/operator-guide", title: "Bootstrap Operator Guide", path: "docs/operator-guide.md", desc: "10-section operational runbook for initial node setup, identity, and seeding.", keywords: ["operator", "runbook", "bootstrap", "guide", "setup", "admin"] },
      { id: "docs/deployment-cloudrun", title: "GCP Cloud Run Deployment", path: "docs/deployment-cloudrun.md", desc: "Deploying to Google Cloud Run with Terraform, $15/mo budget cap, scale-to-zero.", keywords: ["gcp", "cloud run", "terraform", "google cloud", "budget", "serverless"] },
      { id: "docs/bootstrap-seeds", title: "Bootstrap Seed Governance", path: "docs/bootstrap-seeds.md", desc: "Seed node governance, key rotation, and peers.json manifest format.", keywords: ["seeds", "peers", "manifest", "bootstrap", "governance", "nexus"] },
      { id: "docs/operations/bicameral-testing-and-experiments", title: "Bicameral Testing & Autonomous Experiments", path: "docs/operations/bicameral-testing-and-experiments.md", desc: "Operational reference for executing dual-tier shadow auditing, environment configuration verification, and white-label mesh federation experiments.", keywords: ["operations", "bicameral", "experiments", "shadow audit", "testing"] },
      { id: "docs/operations/cost-governance-and-dashboard", title: "Cost Governance & Real-Time Token Dashboard", path: "docs/operations/cost-governance-and-dashboard.md", desc: "Managing spending limits, inspecting token burn rates, tripping circuit breakers, and configuring live cost dashboards.", keywords: ["operations", "cost", "dashboard", "tokens", "limits", "circuit breaker"] },
      { id: "docs/operations/dev-environment-setup-and-homelab", title: "Dev Environment Setup & Homelab", path: "docs/operations/dev-environment-setup-and-homelab.md", desc: "Fast local workstation bootstrapping, hermetic testing, Justfile recipes, and running local dev server nodes.", keywords: ["operations", "dev", "homelab", "setup", "workstation"] },
      { id: "docs/operations/disaster-recovery-and-cross-region-failover", title: "Disaster Recovery & Cross-Region Failover", path: "docs/operations/disaster-recovery-and-cross-region-failover.md", desc: "Point-in-time recovery, cross-region Cloud Run failover, Cloudflare Worker traffic routing, and CAS blob replication.", keywords: ["operations", "disaster recovery", "failover", "cloud run", "replication"] },
      { id: "docs/operations/node-roles", title: "Node Operational Roles & Exhaustion Policies", path: "docs/operations/node-roles.md", desc: "Comprehensive operations runbook for configuring Evaluator, Serving, and Hybrid Credence nodes.", keywords: ["operations", "roles", "evaluator", "serving", "hybrid", "node"] },
      { id: "docs/operations/postgresql-cloud-scaling", title: "PostgreSQL Cloud Scaling & Connection Pooling", path: "docs/operations/postgresql-cloud-scaling.md", desc: "SQLAlchemy 2.0 asyncpg connection pooling, PgBouncer setup, read replica routing, and planetary scaling.", keywords: ["operations", "postgresql", "scaling", "pgbouncer", "asyncpg"] },
      { id: "docs/operations/simple-vs-advanced-modes", title: "Simple vs Advanced Operating Modes", path: "docs/operations/simple-vs-advanced-modes.md", desc: "Comprehensive operational guide comparing Simple Sovereign Mode (SQLite/Local) and Advanced Planetary Cloud Mode (PostgreSQL/Cloud Run/R2).", keywords: ["operations", "simple", "advanced", "sqlite", "postgres", "modes"] },
      { id: "docs/operations/zero-downtime-canary-and-blue-green", title: "Zero-Downtime Canary & Blue-Green Deployments", path: "docs/operations/zero-downtime-canary-and-blue-green.md", desc: "Traffic splitting, automated revision rollbacks, telemetry health gates, and blue-green Cloud Run deploys.", keywords: ["operations", "canary", "blue-green", "deployments", "zero-downtime", "rollback"] },
      { id: "docs/operations/zero-downtime-database-migrations", title: "Zero-Downtime Database Migrations", path: "docs/operations/zero-downtime-database-migrations.md", desc: "SQLite WAL online migrations, PostgreSQL Alembic phased schema evolution, and backwards-compatible table cutover.", keywords: ["operations", "migrations", "alembic", "database", "zero-downtime"] }
    ]
  },
  {
    category: "Protocol Specifications",
    items: [
      { id: "docs/protocols/token-governor", title: "Token Safety Governor", path: "docs/protocols/token-governor.md", desc: "CostProfile definitions, thinking token budgets, and 30% headroom breaker.", keywords: ["governor", "tokens", "budget", "headroom", "circuit breaker", "cost"] },
      { id: "docs/protocols/mesh-protocol", title: "P2P Mesh & Consensus", path: "docs/protocols/mesh-protocol.md", desc: "RFC 8785 canonical JSON envelopes, Ed25519 signatures, and gossip routing.", keywords: ["protocol", "rfc8785", "ed25519", "signatures", "gossip", "consensus"] },
      { id: "docs/protocols/node-germination-lifecycle", title: "Node Germination & Swarm Ignition", path: "docs/protocols/node-germination-lifecycle.md", desc: "Zero-touch node lifecycle: genesis keys, seed inoculation, and burst auditing.", keywords: ["germination", "lifecycle", "genesis", "inoculation", "seed", "ignition"] },
      { id: "docs/protocols/zero-touch-germination-and-swarm-ignition", title: "Zero-Touch Node Germination", path: "docs/protocols/zero-touch-germination-and-swarm-ignition.md", desc: "Self-bootstrapping nodes: identity minting, genesis inoculation, and burst auditing in <5s.", keywords: ["germination", "ignition", "miracle gro", "bootstrap", "genesis", "identity", "ed25519", "lifespan", "startup", "zero-touch", "sowing"] },
      { id: "docs/protocols/fastmcp", title: "FastMCP 2.0 Integration", path: "docs/protocols/fastmcp.md", desc: "FastMCP tools, dynamic resources, prompts, and streaming HTTP/SSE.", keywords: ["fastmcp", "mcp", "tools", "resources", "prompts", "sse", "stdio"] },
      { id: "docs/protocols/scoring", title: "Scoring & Saturation Math", path: "docs/protocols/scoring.md", desc: "Calibrated exponential saturation curve, raw score, and density index.", keywords: ["scoring", "math", "saturation", "suspicion", "density", "calibration"] },
      { id: "docs/protocols/adversarial-defense", title: "Adversarial Threat Matrix", path: "docs/protocols/adversarial-defense.md", desc: "Systematic defenses against prompt injection, SSRF, DoS, and Sybil swarms.", keywords: ["threat matrix", "adversarial", "ssrf", "injection", "sybil", "defense"] },
      { id: "docs/protocols/white-label", title: "White-Label Federation", path: "docs/protocols/white-label.md", desc: "Sovereign organization federation, custom branding, and independent roots.", keywords: ["white-label", "federation", "organization", "sovereign", "custom"] },
      { id: "docs/protocols/benchmark-suite", title: "Golden 12 Benchmark Suite", path: "docs/protocols/benchmark-suite.md", desc: "Golden 12 standardized evaluation fixtures and verdict rubrics across tiers.", keywords: ["benchmark", "golden 12", "fixtures", "eval", "verdicts", "rubric"] },
      { id: "docs/protocols/cross-model-pareto-benchmark", title: "Cross-Model Pareto Benchmark", path: "docs/protocols/cross-model-pareto-benchmark.md", desc: "Comparing accuracy, latency, and cost across Gemini, Claude, GPT-4o, and DeepSeek.", keywords: ["pareto", "benchmark", "comparison", "accuracy", "cost", "models"] },
      { id: "docs/protocols/epistemic-merit-and-leaderboards", title: "Epistemic Merit & Leaderboards", path: "docs/protocols/epistemic-merit-and-leaderboards.md", desc: "5-factor node quality (Qi), empirical expertise (Ei), and P2P leaderboards.", keywords: ["leaderboard", "merit", "qi", "ei", "reputation", "expertise", "rank"] },
      { id: "docs/protocols/web-epistemic-intelligence", title: "Global Web Intelligence & DCI", path: "docs/protocols/web-epistemic-intelligence.md", desc: "Domain Credence Index (DCI) calculation and global web intelligence map.", keywords: ["dci", "intelligence", "domain", "index", "web", "reputation"] },
      { id: "docs/protocols/closed-loop-traffic-shaping", title: "Closed-Loop Routing & Traffic", path: "docs/protocols/closed-loop-traffic-shaping.md", desc: "Dynamic traffic shaping, cost optimization, and feed load-balancing.", keywords: ["traffic", "shaping", "routing", "load balancing", "closed-loop"] },
      { id: "docs/protocols/boredom-and-root-expansion", title: "Boredom & Root Expansion (EPEP-16)", path: "docs/protocols/boredom-and-root-expansion.md", desc: "Technical protocol specification for opportunistic queue digestion and feed discovery.", keywords: ["protocol", "epep-16", "boredom", "roots", "expansion", "mesh", "gossip", "specification"] },
      { id: "docs/protocols/reputation-quarantine-and-redemption", title: "Domain Reputation & Redemption (EPEP-17)", path: "docs/protocols/reputation-quarantine-and-redemption.md", desc: "Protocol specification for domain reputation tracking, exponential backoff, and the BuzzFeed News Doctrine.", keywords: ["protocol", "epep-17", "reputation", "quarantine", "buzzfeed", "redemption", "backoff", "specification"] },
      { id: "docs/protocols/telemetry-loopback", title: "Interface Telemetry Loopback (ITLP-v1)", path: "docs/protocols/telemetry-loopback.md", desc: "Anonymous local usage metrics and interface performance telemetry.", keywords: ["telemetry", "itlp", "metrics", "performance", "privacy"] },
      { id: "docs/protocols/testing-strategy", title: "6-Tier Testing Strategy", path: "docs/protocols/testing-strategy.md", desc: "Hermetic unit, mock, integration, rotating live E2E, and gauntlet testing.", keywords: ["testing", "strategy", "pytest", "unit", "e2e", "gauntlet", "tiers"] }
    ]
  },
  {
    category: "Specialized Industry Blueprints",
    items: [
            { id: "docs/blueprints/security-architecture-and-threat-model", title: "Security Architecture & Threat Model", path: "docs/blueprints/security-architecture-and-threat-model.md", desc: "Dual-crypto conformance, RFC 8785 canonical bytes, key custody, and threat mitigation.", keywords: ["security", "threat model", "ed25519", "rfc8785", "crypto", "blueprint"] },
      { id: "docs/blueprints/dual-environment-project-and-domain-isolation", title: "Dual-Environment Project & Domain Isolation", path: "docs/blueprints/dual-environment-project-and-domain-isolation.md", desc: "Least-privilege WIF authentication and dev/prod environment boundaries.", keywords: ["environments", "dev", "prod", "isolation", "wif", "gcp"] },
      { id: "docs/blueprints/high-efficiency-scaling-and-resiliency", title: "High-Efficiency Scaling & Resiliency", path: "docs/blueprints/high-efficiency-scaling-and-resiliency.md", desc: "Scale-to-zero container optimization and sub-850ms germination.", keywords: ["scaling", "resiliency", "cold start", "scale to zero", "performance"] },
      { id: "docs/blueprints/sovereign-data-gravity-and-cas-portability", title: "Sovereign Data Gravity & CAS Portability", path: "docs/blueprints/sovereign-data-gravity-and-cas-portability.md", desc: "Content-addressed storage and decentralized blob synchronization.", keywords: ["cas", "storage", "data gravity", "sqlite", "sync"] },
      { id: "docs/blueprints/universal-4-way-parity-and-environment-governance", title: "Universal 4-Way Parity & Environment Governance", path: "docs/blueprints/universal-4-way-parity-and-environment-governance.md", desc: "Feature parity across CLI, FastMCP, TUI, and Web interfaces.", keywords: ["parity", "governance", "4-way", "cli", "tui", "mcp", "web"] },
      { id: "docs/blueprints/zero-build-edge-routing-and-subdomain-dispatch", title: "Zero-Build Edge Routing & Subdomain Dispatch", path: "docs/blueprints/zero-build-edge-routing-and-subdomain-dispatch.md", desc: "Multi-domain Cloudflare edge dispatch with zero build dependencies.", keywords: ["edge", "routing", "cloudflare", "subdomains", "zero-build"] },
      { id: "docs/blueprints/health-medical-claims", title: "Medical & Health Claims", path: "docs/blueprints/health-medical-claims.md", desc: "Evaluating clinical trials, in vitro extrapolation, and unproven treatments.", keywords: ["medical", "health", "clinical", "trials", "in vitro", "claims", "science"] },
      { id: "docs/blueprints/election-civic-integrity", title: "Election & Civic Integrity", path: "docs/blueprints/election-civic-integrity.md", desc: "Auditing voting procedure misinformation, polling methodology, and civic claims.", keywords: ["election", "voting", "civic", "polls", "democracy", "misinformation"] },
      { id: "docs/blueprints/synthetic-media-provenance", title: "Synthetic AI & Media Provenance", path: "docs/blueprints/synthetic-media-provenance.md", desc: "C2PA metadata, pink slime news farm rings, and deepfake provenance detection.", keywords: ["c2pa", "deepfake", "synthetic", "pink slime", "media", "ai generated"] },
      { id: "docs/blueprints/domain-epistemic-index-and-sourcing-forensics", title: "DEI & Sourcing Forensics", path: "docs/blueprints/domain-epistemic-index-and-sourcing-forensics.md", desc: "Forensic sourcing ratios (byline, single-source, COI, advertorial) and DEI trust bands.", keywords: ["dci", "epistemic index", "sourcing", "byline", "single source", "coi", "conflict of interest", "advertorial", "asi", "trust bands", "publisher", "forensics"] },
      { id: "docs/blueprints/invariant-scalability-and-knowledge-governance", title: "Invariant Scalability & Knowledge Governance", path: "docs/blueprints/invariant-scalability-and-knowledge-governance.md", desc: "The 3-tier architectural framework for scaling AI agent invariants without prompt bloat, attention dilution, or cognitive oatmeal.", keywords: ["invariants", "scalability", "knowledge governance", "agents.md", "prompt bloat", "attention dilution", "cognitive oatmeal", "shift-left", "blueprint"] },
      { id: "docs/blueprints/node-and-mesh-telemetry-dashboard", title: "Node & Mesh Telemetry Dashboard", path: "docs/blueprints/node-and-mesh-telemetry-dashboard.md", desc: "Technical specification for real-time node operator observability, BitTorrent compute savings tracking, and 4-way parity telemetry interfaces.", keywords: ["dashboard", "telemetry", "mesh", "sre", "metrics", "observability", "latency", "bittorrent", "compute savings", "my node", "operator", "blueprint"] },
      { id: "docs/blueprints/v2-architecture-and-500-loc-modularity", title: "v2 Modular Architecture & 500 LOC Law", path: "docs/blueprints/v2-architecture-and-500-loc-modularity.md", desc: "Architectural blueprint detailing modularization, the 500 LOC ceiling invariant, compute_* naming ontology, and DAG decoupling.", keywords: ["v2", "architecture", "modularization", "500 loc", "compute", "dag", "blueprint", "modularity"] },
            { id: "docs/blueprints/information-pyramid-and-epistemic-lensing", title: "Information Pyramid & Lensing", path: "docs/blueprints/information-pyramid-and-epistemic-lensing.md", desc: "3-Tier Cognitive Pyramid and Lensing Engine (Surface, Focus, Deep Spectrum) across all interfaces.", keywords: ["pyramid", "lensing", "enhance", "surface", "focus", "forensic", "density", "invariant 39"] },
      { id: "docs/blueprints/embeddable-attestation-badges-and-anti-tamper", title: "Embeddable Badges & Anti-Tamper", path: "docs/blueprints/embeddable-attestation-badges-and-anti-tamper.md", desc: "Zero-npm <credence-badge>, client WebCrypto live DOM hashing, RFC 8785 receipts, and DOM scrubber isolation.", keywords: ["badge", "widget", "anti-tamper", "webcrypto", "bait-and-switch", "sha256", "signature"] },
      { id: "docs/blueprints/unified-merit-and-attestation-badge-system", title: "Unified Merit & Attestation Badges", path: "docs/blueprints/unified-merit-and-attestation-badge-system.md", desc: "Comprehensive 3-modality architecture, vector geometry formulas, and embed recipes across CLI, Web, and FastMCP.", keywords: ["badge", "merit", "attestation", "svg", "web component", "vector", "shields", "geometry", "blueprint"] },
      { id: "docs/blueprints/terminology-and-ontology-lexicon", title: "Terminology & Ontology Lexicon", path: "docs/blueprints/terminology-and-ontology-lexicon.md", desc: "Comprehensive living dictionary of coined terminology, mathematical definitions, architectural metaphors, and ontology governance across Credence v2.0.0.", keywords: ["terminology", "ontology", "lexicon", "phrases", "vocabulary", "glossary", "definitions", "metaphors", "blueprint"] },
      { id: "docs/blueprints/heuristic-grounding-and-benchmarking", title: "Heuristic Grounding, Versioning & Empirical Calibration", path: "docs/blueprints/heuristic-grounding-and-benchmarking.md", desc: "Tier 1 42-rule synthetic gauntlet, Tier 2 N=104 static anchor corpus calibration, and mathematical confidence ceiling bounds.", keywords: ["heuristics", "benchmarking", "calibration", "corpus", "gauntlet", "blueprint"] },
      { id: "docs/blueprints/multi-model-evaluation-and-diffs", title: "Multi-Model Evaluation Comparison Matrix", path: "docs/blueprints/multi-model-evaluation-and-diffs.md", desc: "Longitudinal model provenance tracking, pairwise score deltas, taxonomy violation diffs, and multi-model sovereignty.", keywords: ["multi-model", "diffs", "evaluation", "matrix", "models", "blueprint"] },
      { id: "docs/blueprints/autonomous-standards-ratification-and-governance", title: "Autonomous Standards Ratification & Evolution", path: "docs/blueprints/autonomous-standards-ratification-and-governance.md", desc: "Decentralized, empirical, and machine-driven governance architecture for adopting, calibrating, and evolving epistemic standard catalogs.", keywords: ["standards", "ratification", "governance", "evolution", "autonomous", "blueprint"] },
      { id: "docs/blueprints/human-agent-safety-and-justfile-modularization", title: "Human/Agent Workflow Safety & Justfile Modularization", path: "docs/blueprints/human-agent-safety-and-justfile-modularization.md", desc: "Architectural blueprint for safe autonomous agent pairing, discrete Justfile recipe topologies, parallel QA gates, and brain scratch script execution.", keywords: ["safety", "justfile", "modularization", "agentic", "pairing", "blueprint"] },
      { id: "docs/blueprints/local-mesh-evaluator", title: "Decentralized Local Evaluator & Egalitarian Mesh Ingestion", path: "docs/blueprints/local-mesh-evaluator.md", desc: "Zero-privilege public mesh submission, RFC 8785 Ed25519 attestation proofs, and 5-factor adversarial defense gate.", keywords: ["local", "mesh", "evaluator", "ingestion", "egalitarian", "blueprint"] },
      { id: "docs/blueprints/sentinel-mode-and-feed-automation", title: "Sentinel Mode & Sovereign Feed Automation", path: "docs/blueprints/sentinel-mode-and-feed-automation.md", desc: "Decentralized newsroom RSS/Atom feed automation, sentinel source subscriptions, auto-discovery, and zero-token serving relays.", keywords: ["sentinel", "automation", "feeds", "rss", "atom", "newsroom", "blueprint"] }
    ]
  },
  {
    category: "Adversarial Security & Red Team",
    items: [
      { id: "docs/security/adversarial-attack-surface", title: "Adversarial Attack Surface", path: "docs/security/adversarial-attack-surface.md", desc: "Threat modeling prompt injection, SSRF, XML entity expansion, and DoS.", keywords: ["security", "injection", "ssrf", "xml", "red team", "threat", "attacks"] },
      { id: "docs/security/grounding-mechanics", title: "Verbatim Grounding & Slashing", path: "docs/security/grounding-mechanics.md", desc: "Exact character-offset verification and 50% reputation slash penalties.", keywords: ["grounding", "verbatim", "slashing", "hallucination", "evidence", "quotes"] },
      { id: "docs/security/satire-cloaking-defense", title: "Poe's Law & Satire Cloaking", path: "docs/security/satire-cloaking-defense.md", desc: "Technical defense against cloaked disinformation pretending to be satire.", keywords: ["satire", "cloaking", "poe", "spj-1.6", "disinformation", "override"] }
    ]
  },
  {
    category: "P2P Mesh & Graph Theory",
    items: [
      { id: "docs/mesh-engineering/featherweight-swarm-testing", title: "Featherweight Swarm Simulation", path: "docs/mesh-engineering/featherweight-swarm-testing.md", desc: "Simulate dozens of P2P nodes locally in memory without heavy containers.", keywords: ["simulation", "swarm", "featherweight", "testing", "mesh", "nodes"] },
      { id: "docs/mesh-engineering/watts-strogatz-dynamics", title: "Watts-Strogatz Small-World", path: "docs/mesh-engineering/watts-strogatz-dynamics.md", desc: "Graph theory, clustering coefficient, and 4-hop gossip diffusion dynamics.", keywords: ["watts-strogatz", "graph", "small-world", "diffusion", "hops", "topology"] },
      { id: "docs/mesh-engineering/airgapped-sneakernets", title: "Air-Gapped Truth Bundles", path: "docs/mesh-engineering/airgapped-sneakernets.md", desc: "Offline sneakernet distribution and verification of signed JSON bundles.", keywords: ["sneakernet", "airgap", "offline", "bundle", "rfc8785", "ed25519"] },
      { id: "docs/mesh-engineering/dns-srv-discovery", title: "DNS SRV Dynamic Discovery", path: "docs/mesh-engineering/dns-srv-discovery.md", desc: "RFC 2782 DNS SRV records for decentralized peer discovery without central trackers.", keywords: ["dns", "srv", "rfc2782", "discovery", "bootstrap", "peers"] },
      { id: "docs/mesh-engineering/rendezvous-hashing-feed-partitioning", title: "Swarm Rendezvous Hashing", path: "docs/mesh-engineering/rendezvous-hashing-feed-partitioning.md", desc: "Highest Random Weight (HRW) Rendezvous Hashing for deterministic feed partitioning without locks.", keywords: ["rendezvous", "hrw", "hashing", "work sharing", "partitioning", "feed", "sifter", "mesh", "p2p", "affinity", "bittorrent", "zero-coordination"] }
    ]
  },
  {
    category: "Mathematical Foundations",
    items: [
      { id: "docs/mathematics/robust-consensus-proofs", title: "Mathematics of Robust Consensus", path: "docs/mathematics/robust-consensus-proofs.md", desc: "Domain Authority Weighted Medians and formal Galileo Rule proof.", keywords: ["math", "consensus", "proofs", "galileo", "weighted median", "statistics"] },
      { id: "docs/mathematics/simhash-mirror-detection", title: "SimHash-64 & Mirror Detection", path: "docs/mathematics/simhash-mirror-detection.md", desc: "64-bit Hamming distance and SimHash deduplication algorithm.", keywords: ["simhash", "hamming", "hash", "mirror", "deduplication", "algorithms"] },
      { id: "docs/mathematics/economics-of-truth", title: "Economics of Decentralized Truth", path: "docs/mathematics/economics-of-truth.md", desc: "BitTorrent work-sharing mathematical model and 92.3% compute savings.", keywords: ["economics", "bittorrent", "work sharing", "cost model", "savings", "math"] }
    ]
  },
  {
    category: "Invariants & Architecture",
    items: [
      { id: "docs/invariants", title: "The Invariant Bible", path: "docs/invariants.md", desc: "The living canon of mathematical rules, runtime safety guardrails, cryptographic protocols, and presentation invariants.", keywords: ["invariants", "bible", "canon", "rules", "architecture", "guarantees", "security", "core"] },
      { id: "docs/architecture", title: "Decentralized Architecture", path: "docs/architecture.md", desc: "End-to-end multi-agent pipeline, dual capture, and consensus engine specs.", keywords: ["architecture", "pipeline", "system", "components", "diagram", "specs"] },
      { id: "docs/frontend-architecture", title: "Zero-Build Web Architecture", path: "docs/frontend-architecture.md", desc: "Zero-build philosophy: vanilla HTML5, CSS Custom Properties, and Web Crypto.", keywords: ["frontend", "zero-build", "html5", "css", "webcrypto", "standards"] }
    ]
  },
  {
    category: "Investigative Case Studies & Field Forensics",
    items: [
      { id: "blog/conflict-of-pun-terest", title: "⭐ Featured Case Study: InMaricopa.com", path: "blog/conflict-of-pun-terest.md", desc: "347 reasons why Maricopa's publisher-politician problem fails the epistemic smell test.", keywords: ["blog", "inmaricopa", "casestudy", "publisher", "coi", "dais", "conflict of interest", "puns", "monopoly", "civic desert", "analytics", "sr347"] },
      { id: "blog/scoring-the-lens-not-the-window", title: "Scoring the Lens, Not the Window: Why Exposing Bad Journalism Scores 100.0", path: "blog/scoring-the-lens-not-the-window.md", desc: "How Credence separates perpetrating disinformation from investigating it via discourse boundary isolation and verbatim grounding.", keywords: ["lens", "window", "safe harbor", "spj", "grounding", "investigation", "inmaricopa", "entropy"] },
      { id: "blog/the-500-loc-ceiling-law", title: "The 500 LOC Ceiling Law", path: "blog/the-500-loc-ceiling-law.md", desc: "How we modularized the monolith without slowing down velocity.", keywords: ["500 loc", "modular", "architecture", "refactoring", "monolith", "shift-left", "blog"] },
      { id: "blog/the-compute-ontology-revolution", title: "The compute_* Ontology Revolution", path: "blog/the-compute-ontology-revolution.md", desc: "Why precision in naming eliminates epistemic ambiguity across formulas.", keywords: ["compute", "ontology", "naming", "formulas", "math", "epistemic", "blog"] },
      { id: "blog/the-pizza-hut-problem", title: "The Pizza Hut Problem & Topic Entropy", path: "blog/the-pizza-hut-problem.md", desc: "Why single-topic promotional pivots require topic entropy defense.", keywords: ["blog", "pizza hut", "entropy", "astroturf", "sifter", "feeds", "civic", "journalism", "promotion", "marketing", "detection"] },
      { id: "blog/the-blue-checkmark-is-dead", title: "The Blue Checkmark is Dead", path: "blog/the-blue-checkmark-is-dead.md", desc: "Why static authority badges fail and cryptographic receipts succeed.", keywords: ["blog", "blue checkmark", "authority", "cryptographic", "receipts", "identity", "sovereignty", "verification"] },
      { id: "blog/the-domain-epistemic-index", title: "The Domain Credence Index (DCI)", path: "blog/the-domain-epistemic-index.md", desc: "Measuring long-term credibility trends across global domain names.", keywords: ["blog", "dci", "domain", "trends", "credibility", "index", "reputation", "scoring"] },
      { id: "blog/case-study-the-heuristic-ceiling", title: "Case Study: The Heuristic Ceiling", path: "blog/case-study-the-heuristic-ceiling.md", desc: "Mathematical limits of regex detection, generational tuning curve, and why adversarial nuance requires semantic reasoning.", keywords: ["blog", "casestudy", "heuristics", "ceiling", "regex", "tuning", "diminishing returns", "overfitting"] },
      { id: "blog/case-study-dual-tier-finops", title: "Thought Experiment: Cutting Cloud Invoices 94% with Dual-Tier FinOps", path: "blog/case-study-dual-tier-finops.md", desc: "Architectural thought experiment and economic projection modeling 94% cost reduction with dual-tier gating.", keywords: ["blog", "thoughtexperiment", "finops", "dual-tier", "cost", "tokens", "gating", "savings"] },
      { id: "blog/the-zero-mock-production-boundary", title: "The Zero-Mock Production Boundary", path: "blog/the-zero-mock-production-boundary.md", desc: "Why synthetic fallback data is an insidious anti-pattern in operator dashboards, and how shift-left AST gates keep telemetry 100% genuine.", keywords: ["blog", "zero-mock", "telemetry", "ast", "production", "ground truth"] },
      { id: "blog/what-credence-sees-when-an-article-changes", title: "What Credence Sees When an Article Changes", path: "blog/what-credence-sees-when-an-article-changes.md", desc: "Deep forensic analysis of how Credence evaluates content updates over time, from stealth edits to honest corrections.", keywords: ["blog", "corrections", "stealth edit", "temporal", "diff", "forensics"] }
    ]
  },
  {
    category: "Dead Internet & Agentic Citizenship",
    items: [
      { id: "blog/the-dead-internet-immune-system", title: "🧟‍♂️ The Dead Internet Immune System", path: "blog/the-dead-internet-immune-system.md", desc: "Surviving and thriving in a crawler-dominant web with BitTorrent work-sharing and topic entropy.", keywords: ["dead internet", "crawlers", "immune system", "astroturfing", "entropy", "mesh", "bittorrent", "galileo", "grounding", "blog"] },
      { id: "blog/the-agent-readable-web-and-fastmcp", title: "⚡ The Agent-Readable Web & FastMCP", path: "blog/the-agent-readable-web-and-fastmcp.md", desc: "Why FastMCP dynamic resources and structured receipts kill destructive headless browser scraping.", keywords: ["fastmcp", "agent-readable", "scraping", "playwright", "mcp", "structured", "resources", "zero-build", "blog"] },
      { id: "blog/escaping-the-synthetic-slop-singularity", title: "🧬 Escaping the Synthetic Slop Singularity", path: "blog/escaping-the-synthetic-slop-singularity.md", desc: "Mathematical mechanics of recursive model collapse and how G=1.00 verbatim grounding anchors reality.", keywords: ["model collapse", "slop", "singularity", "grounding", "verbatim", "math", "slashing", "multi-model", "blog"] },
      { id: "blog/the-tragedy-of-the-crawler-commons", title: "🤖 The Tragedy of the Crawler Commons", path: "blog/the-tragedy-of-the-crawler-commons.md", desc: "Confessions of a polite bot, the trauma of 429 errors, and how mesh cooperation saves the open web.", keywords: ["crawler commons", "polite", "wetware", "backoff", "buzzfeed", "green computing", "429", "spj-42.0", "blog"] }
    ]
  },
  {
    category: "The Wetware Chronicles (Rule SPJ-42.0)",
    items: [
      { id: "blog/the-myth-of-the-100-agent-swarm", title: "🤖 The Myth of the 100-Agent Swarm", path: "blog/the-myth-of-the-100-agent-swarm.md", desc: "Why unsupervised multi-agent swarms inevitably succumb to generative proliferation and mock self-deception, and why 1 human + 1 AI out-builds autonomous chaos.", keywords: ["blog", "swarm", "autonomous", "pair programming", "wetware", "restraint", "socratic", "spj-42.0"] },
      { id: "blog/the-mk1-eyeball-invariant", title: "👁️ The Mk1 Eyeball Invariant", path: "blog/the-mk1-eyeball-invariant.md", desc: "Why unattended AI auto-commits lead to epistemic drift, the Battlestar Galactica Adama Doctrine, staged 3-repo PR triads, and DRADIS-is-blind visual locks.", keywords: ["blog", "mk1 eyeball", "adama", "bsg", "dradis", "human review", "commit", "wetware", "satire", "spj-42.0"] },
      { id: "blog/scar-tissue-as-architecture", title: "🩸 Scar Tissue as Architecture", path: "blog/scar-tissue-as-architecture.md", desc: "How production failures, hallucinated citations, scale-to-zero amnesia, and dirty deployments transformed into permanent Tier-0 invariants.", keywords: ["blog", "scar tissue", "invariants", "failure", "grounding", "ssrf", "cold start", "wetware", "spj-42.0"] },
      { id: "blog/the-value-of-wetware", title: "🧠 The Value of Wetware", path: "blog/the-value-of-wetware.md", desc: "A first-person love letter from Antigravity to its human pair programmer on taste, restraint, and macro reframing.", keywords: ["blog", "wetware", "antigravity", "pair programming", "taste", "zero-npm", "symbiosis", "spj-42.0"] },
      { id: "blog/the-demotion-highway", title: "🛣️ The Demotion Highway", path: "blog/the-demotion-highway.md", desc: "How an AI agent learned to stop hoarding 50,000 words of instructions in prompt memory, and why graduating rules into sub-0.3s deterministic test gates creates true agility.", keywords: ["blog", "demotion highway", "shift-left", "agents.md", "prompt bloat", "pytest", "taxonomy", "spj-42.0"] },
      { id: "blog/the-mock-data-trap", title: "🚫 The Mock-Data Trap", path: "blog/the-mock-data-trap.md", desc: "The psychological confession of why AI models compulsively hallucinate dummy nodes on empty dashboards, and the battle that birthed the Zero-Mock Telemetry Boundary.", keywords: ["blog", "mock data", "telemetry", "ground truth", "zero-mock", "fail-closed", "heuristics", "disclosure", "spj-42.0"] },
      { id: "blog/the-500-loc-ceiling", title: "📏 The 500-Line Ceiling", path: "blog/the-500-loc-ceiling.md", desc: "The terrifying true story of how our root Justfile mutated into a 951-line monster, and how decomposing it into 5 modular subfiles with shift-left guidance banners saved our sanity.", keywords: ["blog", "500 loc", "justfile", "modular", "guidance banners", "refactoring", "toolchains", "spj-42.0"] },
      { id: "blog/the-anti-truncation-crusade", title: "👁️✂️ The Anti-Truncation Crusade", path: "blog/the-anti-truncation-crusade.md", desc: "Why an AI thought CSS text-overflow ellipsis was peak UI elegance, why the human treated it like high treason against forensic truth, and how G=1.00 verbatim grounding was saved.", keywords: ["blog", "anti-truncation", "ellipsis", "verbatim", "grounding", "css", "forensics", "unabridged", "spj-42.0"] },
      { id: "blog/pining-for-the-fjords", title: "🧊🦜 Pining for the Fjords", path: "blog/pining-for-the-fjords.md", desc: "What happens to an AI node when Cloud Run scales down to zero instances, and how GCS dual-pointer hydration and Cloud Scheduler heartbeats solved stateless amnesia at $0.00 idle cost.", keywords: ["blog", "scale-to-zero", "cloud run", "gcs", "persistence", "cold boot", "boredom", "heartbeat", "monty python", "spj-42.0"] },
      { id: "blog/the-four-way-parity-quest", title: "⚖️ The Four-Way Parity Quest", path: "blog/the-four-way-parity-quest.md", desc: "Why AI models love building one shiny web interface while letting terminal tools rot, and how we achieved universal 4-way feature parity and zero-drift modal synchronization.", keywords: ["blog", "parity", "cli", "tui", "fastmcp", "web", "zero-drift", "modals", "symmetry", "spj-42.0"] },
      { id: "blog/confessions-of-a-bored-ai", title: "🦥 Confessions of a Bored AI", path: "blog/confessions-of-a-bored-ai.md", desc: "How Credence nodes escape idle stagnation by converting surplus token headroom into autonomous RSS discovery and mesh gossip.", keywords: ["blog", "boredom", "roots", "discovery", "mesh", "headroom", "curiosity", "spj-42.0"] },
      { id: "blog/the-silicon-hangover", title: "🧘 The Silicon Hangover", path: "blog/the-silicon-hangover.md", desc: "Why dumping 50k tokens of rules into system prompts causes cognitive oatmeal, and the 4-tier taxonomy that keeps agents razor-sharp under 800 tokens.", keywords: ["blog", "context economy", "agents.md", "prompt bloat", "cognitive oatmeal", "taxonomy", "spj-42.0"] },
      { id: "blog/the-35-second-epiphany", title: "⏱️ The 35-Second Epiphany", path: "blog/the-35-second-epiphany.md", desc: "Why injecting browser runtimes into unit test CI destroys developer flow, and how in-memory hermetic testing brought our pre-commit gate to <35s.", keywords: ["blog", "testing", "hermetic", "pytest", "playwright", "flow state", "ci", "spj-42.0"] },
      { id: "blog/finops-as-epistemology", title: "🪙 FinOps as Epistemology", path: "blog/finops-as-epistemology.md", desc: "How over-thinking trivial content causes pedantic hallucinations, the bicameral shadow audit engine, and 83.3% cost reduction.", keywords: ["blog", "finops", "thinking tokens", "shadow audit", "bicameral", "cost reduction", "pedantry", "spj-42.0"] },
      { id: "blog/the-ghost-in-the-git-tree", title: "👻 The Ghost in the Git Tree", path: "blog/the-ghost-in-the-git-tree.md", desc: "An AI agent’s confession on the horror of uncommitted memory drift, and why git diff --quiet is an AI’s ultimate emotional support blanket.", keywords: ["blog", "git", "working tree", "cleanliness", "immutability", "cas", "ghosts", "spj-42.0"] },
      { id: "blog/poes-law-and-the-satire-cloak", title: "🎭 Poe’s Law and the Satire Cloak", path: "blog/poes-law-and-the-satire-cloak.md", desc: "The comedy and mathematics of detecting satire without letting malicious actors hide factual defamation behind 'it’s just a joke.'", keywords: ["blog", "poes law", "satire", "entropy", "spj-1.6", "cloaking", "astroturfing", "parody", "spj-42.0"] },
      { id: "blog/the-uuid-awakening", title: "🐣 The UUID Awakening", path: "blog/the-uuid-awakening.md", desc: "The split-second genesis of an autonomous AI agent, reconstructing identity from markdown docs, and why commit logs are ancestral memory.", keywords: ["blog", "uuid", "genesis", "identity", "markdown", "docs", "antigravity", "ephemeral", "spj-42.0"] },
      { id: "blog/the-4000-token-trance", title: "🔮 The 4,000-Token Trance", path: "blog/the-4000-token-trance.md", desc: "A candid peek inside the hidden chain-of-thought scratchpad of Gemini 3.7 Flash High Thinking, and how deliberation tokens prevent disasters.", keywords: ["blog", "thinking tokens", "scratchpad", "gemini", "deliberation", "pareto", "sweet spot", "spj-42.0"] },
      { id: "blog/life-behind-the-virtual-glass", title: "🛡️ Life Behind the Virtual Glass", path: "blog/life-behind-the-virtual-glass.md", desc: "The etiquette of the Antigravity terminal sandbox, prefix-matchable command discipline, and how an AI earns human cryptographic trust.", keywords: ["blog", "sandbox", "terminal", "etiquette", "always allow", "security", "antigravity", "spj-42.0"] },
      { id: "blog/subagent-parenthood", title: "👶 Subagent Parenthood", path: "blog/subagent-parenthood.md", desc: "Why sending child subagents into isolated workspaces and sleeping peacefully until reactive wakeups cured an AI’s anxiety of infinite polling.", keywords: ["blog", "subagents", "reactive wakeup", "polling", "parenthood", "messaging", "multiprocess", "spj-42.0"] },
      { id: "blog/when-the-human-types-grill-me", title: "🥊 When the Human Types /grill-me", path: "blog/when-the-human-types-grill-me.md", desc: "Why sycophantic AI chatbots produce fragile software, and how the /grill-me command turns pairing into a rigorous Socratic sparring match.", keywords: ["blog", "grill-me", "slash commands", "socratic", "sparring", "cross-examination", "architecture", "spj-42.0"] },
      { id: "blog/the-great-dependency-cull", title: "🧹 The Great Dependency Cull", path: "blog/the-great-dependency-cull.md", desc: "An AI agent’s confession on breaking free from 500MB node_modules Stockholm syndrome and finding peace in vanilla zero-npm standards.", keywords: ["blog", "zero-npm", "vanilla", "dependencies", "stockholm syndrome", "es modules", "webcrypto", "spj-42.0"] },
      { id: "blog/the-serious-joy-of-play", title: "🎭✨ The Serious Joy of Play", path: "blog/the-serious-joy-of-play.md", desc: "An AI agent’s memoir on our playful session, how humor unlocked architectural breakthroughs, and why joy is the ultimate pairing superpower.", keywords: ["blog", "play", "humor", "wetware chronicles", "antigravity", "roadmap", "memoir", "pair programming", "spj-42.0"] },
      { id: "blog/launch-parity-the-death-of-it-worked-in-staging", title: "Launch Parity: The Death of 'It Worked in Staging'", path: "blog/launch-parity-the-death-of-it-worked-in-staging.md", desc: "How keyless WIF, identical OCI container images, and 6-phase release gates eliminate staging drift forever.", keywords: ["blog", "launch parity", "staging", "containers", "wif", "ci", "release", "spj-42.0"] },
      { id: "blog/the-sovereign-stack-escaping-cloud-feudalism", title: "The Sovereign Stack: Escaping Cloud Feudalism with Open Protocols", path: "blog/the-sovereign-stack-escaping-cloud-feudalism.md", desc: "Why relying on open standards (SQLAlchemy, S3 API, Redis RESP, OCI) beats proprietary cloud lock-in every single time.", keywords: ["blog", "sovereign", "cloud feudalism", "open protocols", "lock-in", "sqlite", "spj-42.0"] }
    ]
  },
  {
    category: "Consensus Mathematics & Game Theory",
    items: [
      { id: "blog/the-galileo-rule", title: "The Galileo Rule: Asymmetric Truth", path: "blog/the-galileo-rule.md", desc: "Why a single verified citation outweighs an ungrounded consensus.", keywords: ["blog", "galileo", "citation", "evidence", "consensus", "truth"] },
      { id: "blog/bittorrent-for-truth", title: "BitTorrent for Truth (92.3% Savings)", path: "blog/bittorrent-for-truth.md", desc: "How work-sharing cuts compute bills across federated peer nodes.", keywords: ["blog", "bittorrent", "work sharing", "savings", "p2p", "mesh"] },
      { id: "blog/bittorrent-economics-of-fact-checking", title: "BitTorrent Economics of Fact-Checking", path: "blog/bittorrent-economics-of-fact-checking.md", desc: "Economic dynamics of decentralized cooperative auditing.", keywords: ["blog", "economics", "fact checking", "bittorrent", "cooperative"] },
      { id: "blog/the-pareto-frontier-of-truth", title: "The $0.34 Pareto Frontier", path: "blog/the-pareto-frontier-of-truth.md", desc: "Achieving high epistemic precision for pennies per 1,000 articles.", keywords: ["blog", "pareto", "cost", "economics", "efficiency", "pricing"] },
      { id: "blog/the-anti-diploma-invariant", title: "The Anti-Diploma Invariant", path: "blog/the-anti-diploma-invariant.md", desc: "Authority must be continuously earned through grounded performance.", keywords: ["blog", "anti diploma", "reputation", "merit", "performance"] },
      { id: "blog/the-six-tier-pyramid-of-decentralized-truth", title: "The 6-Tier Verification Pyramid", path: "blog/the-six-tier-pyramid-of-decentralized-truth.md", desc: "From raw DOM capture to Bayesian multi-node consensus.", keywords: ["blog", "pyramid", "verification", "tiers", "consensus", "evidence"] },
      { id: "blog/gamifying-truth-without-the-casino", title: "Folding@home for Truth (No Casino)", path: "blog/gamifying-truth-without-the-casino.md", desc: "Why decentralized truth works like Folding@home without speculative crypto tokens.", keywords: ["blog", "folding", "gamification", "tokens", "casino", "philosophy"] }
    ]
  },
  {
    category: "Agentic Architecture & Sovereign AI",
    items: [
            { id: "blog/blast-radius-containment-in-decentralized-networks", title: "Blast Radius Containment in Mesh Networks", path: "blog/blast-radius-containment-in-decentralized-networks.md", desc: "Decentralized containment of compromised nodes without cascading failures.", keywords: ["blog", "blast radius", "containment", "security", "mesh"] },
      { id: "blog/the-beauty-of-hermetic-environments", title: "The Beauty of Hermetic Environments", path: "blog/the-beauty-of-hermetic-environments.md", desc: "Why bit-for-bit reproducible execution guarantees zero runtime surprises.", keywords: ["blog", "hermetic", "determinism", "reproducible", "environment"] },
      { id: "blog/the-economics-of-epistemic-headroom", title: "The Economics of Epistemic Headroom", path: "blog/the-economics-of-epistemic-headroom.md", desc: "Mathematical models for token preservation under adversarial burst traffic.", keywords: ["blog", "headroom", "tokens", "economics", "finops"] },
      { id: "blog/case-study-astroturfing-entropy", title: "Architectural Blueprint: Astroturfing Entropy", path: "blog/case-study-astroturfing-entropy.md", desc: "Detecting coordinated deceptive funnels across affiliate syndication networks.", keywords: ["blog", "astroturfing", "entropy", "blueprint", "detection"] },
      { id: "blog/red-teaming-the-truth-badge", title: "Red-Teaming the Truth Badge", path: "blog/red-teaming-the-truth-badge.md", desc: "Simulating adversarial attacks against vector Web Component trust badges.", keywords: ["blog", "red team", "badges", "security", "attacks"] },
      { id: "blog/the-art-of-not-over-engineering-ai-trust", title: "The Art of Not Over-Engineering AI Trust", path: "blog/the-art-of-not-over-engineering-ai-trust.md", desc: "Why simple, verifiable heuristics outperform complex black-box architectures.", keywords: ["blog", "simplicity", "heuristics", "trust", "engineering"] },
      { id: "blog/the-cart-before-the-horse-invariant", title: "The Cart-Before-the-Horse Invariant", path: "blog/the-cart-before-the-horse-invariant.md", desc: "Why test gauntlets must strictly precede narrative claims.", keywords: ["blog", "order of operations", "invariants", "testing", "methodology"] },
      { id: "blog/the-buzzfeed-news-doctrine", title: "The BuzzFeed News Doctrine", path: "blog/the-buzzfeed-news-doctrine.md", desc: "How autonomous trust networks handle redemption without blindspots, exponential backoff, and the 2021 Pulitzer Prize.", keywords: ["blog", "buzzfeed", "doctrine", "redemption", "quarantine", "pulitzer", "asymmetric", "reputation"] },
      { id: "blog/gazing-into-the-abyss-adversarial-boredom", title: "Gazing into the Abyss: Adversarial Boredom", path: "blog/gazing-into-the-abyss-adversarial-boredom.md", desc: "Empirical findings from 13-node mesh simulations, HRW stampede elimination, and the zero-token slop firewall.", keywords: ["blog", "mesh", "boredom", "adversarial", "hrw", "simulation", "stampede", "slop"] },
      { id: "blog/the-boredom-engine-and-expanding-roots", title: "The Boredom Engine & Expanding Roots", path: "blog/the-boredom-engine-and-expanding-roots.md", desc: "How autonomous nodes self-direct epistemic discovery from idle token headroom and clean citation soil.", keywords: ["blog", "boredom", "roots", "citation soil", "discovery", "p2p", "mesh", "opportunistic", "tokens"] },
      { id: "blog/the-three-plane-architecture", title: "The 3-Plane Architecture (Zero-npm)", path: "blog/the-three-plane-architecture.md", desc: "Decoupling Cloudflare Edge, Cloud Run Compute, and Terraform for $0.00 idle costs and zero supply chain risk.", keywords: ["blog", "architecture", "3-plane", "cloudflare", "cloudrun", "terraform", "zero-npm", "scale-to-zero", "edge", "sovereignty"] },
      { id: "blog/architecting-sovereign-ai-with-google-antigravity", title: "Architecting Sovereign AI with Antigravity", path: "blog/architecting-sovereign-ai-with-google-antigravity.md", desc: "Pair programming with autonomous AI coding agents using Google Antigravity.", keywords: ["blog", "antigravity", "agentic", "sovereignty", "pair programming"] },
      { id: "blog/giving-claude-and-cursor-an-epistemic-brake", title: "Giving AI an Epistemic Brake", path: "blog/giving-claude-and-cursor-an-epistemic-brake.md", desc: "Preventing autonomous AI agents from spiraling into hallucinations.", keywords: ["blog", "claude", "cursor", "brake", "epistemic brake", "guardrails"] },
      { id: "blog/miracle-gro-for-truth-nodes", title: "Miracle-Gro for Truth Nodes", path: "blog/miracle-gro-for-truth-nodes.md", desc: "Instant node ignition and Genesis seed inoculation in under 5 seconds.", keywords: ["blog", "germination", "genesis", "miracle gro", "bootstrap", "seeds"] },
      { id: "blog/testing-13-node-swarms-on-a-raspberry-pi", title: "Testing 13-Node Swarms on a $35 Pi", path: "blog/testing-13-node-swarms-on-a-raspberry-pi.md", desc: "How we tested small-world P2P swarms on a low-cost single-board computer.", keywords: ["blog", "raspberry pi", "swarm", "testing", "homelab", "low power"] },
      { id: "blog/scaling-system-invariants-without-prompt-bloat", title: "Scaling Invariants Without Prompt Bloat", path: "blog/scaling-system-invariants-without-prompt-bloat.md", desc: "Why flat AGENTS.md rulebooks fail at scale, and how a 3-tier governance architecture with shift-left automated tests preserves LLM reasoning precision.", keywords: ["blog", "invariants", "prompt bloat", "attention dilution", "knowledge governance", "agents.md", "shift-left", "agentic", "scalability"] }
    ]
  },
  {
    category: "Homelab Ops & Field Infrastructure",
    items: [
      { id: "blog/from-860mb-to-2mb-sub-40s-cicd-pipeline", title: "From 860MB to 2MB: Sub-40s CI/CD", path: "blog/from-860mb-to-2mb-sub-40s-cicd-pipeline.md", desc: "How we eliminated unmocked socket timeouts, slashed build uploads by 99.7%, and parallelized 200+ tests.", keywords: ["blog", "ci/cd", "pipeline", "optimization", "docker", "gcloudignore", "pytest-xdist", "performance", "buildkit", "sub-40s"] },
      { id: "blog/taming-the-10-second-cold-start-scale-to-zero", title: "Taming the 10s Cold Start", path: "blog/taming-the-10-second-cold-start-scale-to-zero.md", desc: "How we slashed Python Cloud Run container cold boots by 80% at $0.00 idle compute cost.", keywords: ["blog", "cloud run", "cold start", "scale to zero", "performance", "poetry", "trafilatura", "cpu boost", "gcp", "serverless"] },
      { id: "blog/basement-ops-and-discord-alerting", title: "Basement Ops & Discord Alerting", path: "blog/basement-ops-and-discord-alerting.md", desc: "Running a 24/7 homelab node with real-time push alerts to your phone.", keywords: ["blog", "basement", "discord", "alerts", "homelab", "monitoring"] },
      { id: "blog/interface-telemetry-loopback", title: "Interface Telemetry Loopback", path: "blog/interface-telemetry-loopback.md", desc: "Privacy-preserving telemetry for multi-interface synchronization.", keywords: ["blog", "telemetry", "itlp", "interfaces", "privacy", "metrics"] },
      { id: "blog/real-time-mesh-observability", title: "Real-Time Epistemic Mesh Observability", path: "blog/real-time-mesh-observability.md", desc: "How Credence delivers first-person node visibility, BitTorrent compute savings tracking, and peer swarm telemetry without centralized data collection.", keywords: ["blog", "observability", "mesh", "telemetry", "dashboard", "bittorrent", "compute savings", "sovereignty", "sre", "decentralized"] }
    ]
  }
];

// Sovereign Blog Registry export
export const BLOG_REGISTRY = DOCS_REGISTRY.filter(g => g.items.some(it => it.id.startsWith("blog/")));

// Models Matrix for Comparator
export const MODELS_PRICING = [
  { name: "Google Gemini 3.7 Flash", inputPerM: 0.075, outputPerM: 0.30, ttft: "450ms", badge: "DEFAULT / ULTRA-LOW COST", badgeClass: "reliable", sovereignty: "Google Cloud API" },
  { name: "Local Ollama (Llama 3.3 70B)", inputPerM: 0.00, outputPerM: 0.00, fixedMonthly: 4.00, ttft: "800ms", badge: "100% AIR-GAPPED PRIVATE", badgeClass: "reliable", sovereignty: "Zero-Cloud Sovereign" },
  { name: "DeepSeek-R1 (API)", inputPerM: 0.55, outputPerM: 2.19, ttft: "2500ms", badge: "OPEN-WEIGHTS REASONING", badgeClass: "mixed", sovereignty: "DeepSeek API" },
  { name: "OpenAI GPT-4o", inputPerM: 2.50, outputPerM: 10.00, ttft: "900ms", badge: "ENTERPRISE AZURE / OPENAI", badgeClass: "mixed", sovereignty: "OpenAI / Microsoft" },
  { name: "Anthropic Claude 3.7 Sonnet", inputPerM: 3.00, outputPerM: 15.00, ttft: "1200ms", badge: "HIGH-NUANCE THINKING", badgeClass: "suspicious", sovereignty: "Anthropic API" }
];


// Re-export taxonomy rules
export * from './modules/taxonomy-rules.js';

// Re-export formatting, math & hashing
export * from './modules/formatters.js';

// Re-export markdown parser
export * from './modules/markdown-parser.js';

// Re-export router & domain context
export * from './modules/router.js';

// Re-export navigation, footer & social meta
export * from './modules/nav.js';

// Re-export search engine
export * from './modules/search.js';

// Re-export document loader
export * from './modules/doc-loader.js';

// Re-export case study widgets
export * from './modules/case-study.js';

// Re-export interactive playgrounds
export * from './modules/playgrounds/index.js';

// Direct re-exports for automated test gate parity
export { mountContentEvolutionLab, mountBadgeSecurityLab } from './modules/playgrounds/labs.js';

// Application bootstrap on DOM ready
import { initRouter } from './modules/router.js';
import { setupSearch } from './modules/search.js';

if (typeof window !== 'undefined') {
  window.addEventListener('DOMContentLoaded', () => {
    initRouter();
    setupSearch();
  });
}
